# Generated by Django 3.1.4 on 2021-03-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdate',
            new_name='OrderUpdates',
        ),
    ]
