# Generated by Django 3.1.4 on 2021-03-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210308_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdates',
            new_name='Orderupdate',
        ),
    ]
